#ifndef __ARGPARSE__
#define __ARGPARSE__

#include <getopt.h>
#include "global.h"
#include "logger.h"
#include "types.h"
#include "http.h"

enum {
    USE_URL=1,
    USE_TEMPLATE
};

extern struct option options[NUM_PARAMS];
// create argparse object
parsed_args_t *create_argparse();
// parse from argc, argv
int argparse(parsed_args_t **this, int argc, char **argv);
// parse url, and use the result to fill host & path
int parse_url(parsed_args_t *this); //char *url, char **host, u16 *port, char **path);
// randomly pick a url and then update
int update_url_info_rand(parsed_args_t **this);
// print usage
void print_config(parsed_args_t *this);
void print_manual(u8 detail);

static const char *a10logo=
"\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXXXXNNWWWWWWWWWWWWWW\n\
WWWMWWWWMWWWWWMWWWWMWWWWMWWWWWMWWWWMWWWWMWWWWWMWWWWMWWWWMWWXXXXXXNNWMWWWWMWWWWWMWWWWM\n\
MMWWWMMWWWWMWWWWMMWWWMMWWWWMWWWWMMWWWMMWWWWMWWWWMMWWWMWNXXXXXNNWWMMWWWMMWWWWMWWWWMMWW\n\
WWWMWWWWMWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXXXNNWWWWWWWWWWMWWWWMMWWWWWWWWWM\n\
WWWWWWWWWWWWWWWWWNKKKKKKKKKKKKKXWWWWWWWWWWWWWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
MWWWWWMWWWWMWWWWWXo,,,;,,,,;;,,c0WWWWMWWWWWWWNXXXXNWWWMWWWWMMMWWWMMWWWMMWWWWMWWWWMWWW\n\
WWWMWWWWMMWWWMMWNO:''''''''''''':0WMWWWWMWNXXXNNKOkdONWWXOxddddddddddddxKWMWWWMMWWWWM\n\
MWWWWWMWWWWWWWWWk;''''''''''''''':0WWWWWNXXX0kdc;'''lXW0c'''.....'..'''';xNWWWWWWWWWW\n\
WWWWWWWWWWWWWWNk;''';oc'''''''''''c0WNNXNWW0:'''''''lXNo'''''':xxxxl''''':0WWWWWWWWNK\n\
WWWMWWWWWWWWWNx,''';OWKc'''''''''''c0NNWWWW0c,,'''''lXKc''''''dNWWWO;.''.,OWWWWWXK00K\n\
MMWWWMMWWWWMNd,''':OWMM0c'''''''''''lKMWWWWWX0l'''''lXK:.'''''oNWMMO;.''',kWNXK0KXNWW\n\
WWWMWWWWMWWXo,''':0WWWWWKc'''''''''''lKWWWWWWNo'''''lX0:.'''.'dWWWWO;.'';lkK0KNWWWWWM\n\
WWWWWWWWWWKl'''''lxxxxxxxl,'''''''''''lXWWWWWNo'''''lX0:''''.'dWWWW0c:odddONWWWWWWWWW\n\
MWWWWWMWWKc'''''''''.''''''''''''''''''oXWWWMNo''.''lXK:.'''.'dNNNXOdol:,,OMWWWWWMWWW\n\
WWWMWWWW0c'''';:::::::::::::,'''''''''''oKXXXXl'''''cK0:'',;:ckKKKXk;'''.,kWWWMMWWWWM\n\
WWWWWWWO:''''oKNNNNNNNXXXXXXk:'''''''''''oKNNKl'''''lK0ocoooood0KXNx,'''';OMWWWWWMWWW\n\
WWWWWNk;''',dNWWWWWWWNXNNNNNWO:'''''''''',oXMNo.',;cdKKkl:;,'',;:::;'''''cKWWWWWWWWWW\n\
WWWWXd,.''.:KMWWWWWWNNNWWWWWWNo'...''.'''''oKXdlodoldKWKd:,,,,,,,,,,,,,;lkKKXNWWWWWWM\n\
MMWNOddddddkXWWWMMWXXWMWWWWMMNkdddddddoollox0XXNNX000NMWNXK000000KK000KXNNNK00KNWMMWW\n\
WWWMWWWWMMWWWWMWWWWWXXNNWWWNNNNNXXXXXXXXNNNNWMMWWWWMWWWWMWWWWWWMWWWWWWWWWWMNKOOKWWWWM\n\
WWWWWWWWWWWWWWWWWWWWWNNXXKXXXXXXNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNX0OOKWWWWW\n\
WWWWWWMWWWWWWWWWWWWWWWWWNNNXXXXNNWWWWWMWWWWWWWWWWWWWWWWWWWWWMWWWWMWWWWNNXK000KNWWWWWW\n\
WWWMWWWWMMWWWMMWWWWMWWWWMMWWNNNXXXXXXXXXNNXXNNNNNNNWNNNNWNNXXXNNXKKKKKKKKXXNNWMMWWWWM\n\
MWWWWWMWWWWMWWWWMMWWWWMWWWWMWWWWMMWNNWNNXXXXXXXXXXKKKXXKKKXXXXKKXXNXNNWWWWWWMWWWWMWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
NWWMMWNWMMWNWMMWWWMMMWWWMMWNWMMWWWMMMWNWMMWNWMMWWWWMWWWWMMWWWWMMWNWWMWWWWMMWNWMMWWWMM\n\
";

#endif